# Generated by Django 3.1.5 on 2021-06-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='detail',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
