# Generated by Django 3.2.4 on 2021-06-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20210617_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.postmodel')),
            ],
        ),
    ]
